<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Reservar</name>
   <tag></tag>
   <elementGuidId>6a2ddf42-1c0b-4407-a286-110abdd50beb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[40]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.result-option__book-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Reservar&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9c5415de-3755-4e51-bbef-cc9c404f8a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f1616537-e946-46ef-ba26-ebbf8444a31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary result-option__book-button</value>
      <webElementGuid>e6c2b121-10ed-4441-a42b-8633f4423213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-optionals</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ef1a3f9f-f20a-4732-943c-308000cb5955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-optionalmode</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>22c8de7c-75e3-450e-9294-390868b0ffc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reservar</value>
      <webElementGuid>2703a386-1cc0-4693-9d8e-9a96e314ed78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;results-list&quot;)/div[@class=&quot;results-list__body js-results-list-placeholder&quot;]/div[@class=&quot;results-list__page results-list__list&quot;]/div[@class=&quot;results-list__item&quot;]/article[@class=&quot;result package-result&quot;]/div[@class=&quot;info-card&quot;]/div[@class=&quot;info-card__content&quot;]/div[@class=&quot;info-card__price&quot;]/button[@class=&quot;btn btn-primary result-option__book-button&quot;]</value>
      <webElementGuid>f3710334-f9e6-48d4-ac46-5881dacccec8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[40]</value>
      <webElementGuid>420c7c43-0921-4de7-8849-308930f8ded4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='results-list']/div[2]/div/div/article/div/div[2]/div[3]/button</value>
      <webElementGuid>dba8989c-e84b-401c-841e-8b3fbcbbcabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 3,700 USD'])[1]/following::button[1]</value>
      <webElementGuid>691764d4-f65e-4f48-ba1f-faea12d78df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Precio desde'])[1]/following::button[1]</value>
      <webElementGuid>d6a9a041-4f83-4ead-92ec-59f95458e548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info'])[1]/preceding::button[1]</value>
      <webElementGuid>18155672-1f60-4746-9fd2-d6d8871f6db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reservar']/parent::*</value>
      <webElementGuid>372c1ff8-9e4a-410e-b8dd-328db1e8de1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/button</value>
      <webElementGuid>119cda16-24b4-4f8d-9bc2-cba083ab4a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Reservar' or . = 'Reservar')]</value>
      <webElementGuid>5b746636-951d-41a4-9211-15b6180f8861</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
