<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Acceder</name>
   <tag></tag>
   <elementGuidId>6d48f381-4892-4555-a0b7-ffa53dfcbf88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.btn-login.js-auto-form-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Acceder&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ecff517-be4d-4c68-aa00-526ff96bbab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f132b21c-83f7-4fe5-af88-ef91f92dde8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-login js-auto-form-submit</value>
      <webElementGuid>60c6637f-401e-48b1-a524-46f740b276c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acceder</value>
      <webElementGuid>92428b24-e3d4-4dad-a478-9994afbee5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prehome-login-multi-login-box-b2bUser-loginBox&quot;)/div[@class=&quot;login-box__section&quot;]/div[@class=&quot;login-box__section-item login-box__section-item--action&quot;]/button[@class=&quot;btn btn-primary btn-login js-auto-form-submit&quot;]</value>
      <webElementGuid>4f139980-e458-4076-ac0c-e311b3dbe4fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>b1ecc899-90c8-4301-ade4-1ddc312c896d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prehome-login-multi-login-box-b2bUser-loginBox']/div[4]/div/button</value>
      <webElementGuid>e8557637-8d20-4138-b61b-7f51606bb39b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Por favor, acepte los términos y condiciones generales.'])[1]/following::button[1]</value>
      <webElementGuid>46e937a3-8105-4daa-a31f-8c8288271fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acepte los términos y condiciones generales'])[1]/following::button[1]</value>
      <webElementGuid>407d6340-f8c6-4cbc-9a8d-b39fe9f2a3bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recuperar contraseña'])[1]/preceding::button[1]</value>
      <webElementGuid>96da8408-bcd3-4b5d-a2e4-f5954d5d3adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regístrese'])[1]/preceding::button[1]</value>
      <webElementGuid>e5fe116f-ab64-4ec3-8543-791204f2abe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Acceder']/parent::*</value>
      <webElementGuid>3f536dfc-079a-481e-9dd0-bfa12dd477c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>42acb666-4a77-4794-bde8-4afebf0b0743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Acceder' or . = 'Acceder')]</value>
      <webElementGuid>97912e0f-a173-4633-839d-6246922bbfb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
