<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Por favor, introduzca la contrasea_pr_d431d7</name>
   <tag></tag>
   <elementGuidId>345fb537-924d-4366-9da4-6640e24e7a78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prehome-login-multi-login-box-b2bUser-loginBox-terms-and-conditions']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prehome-login-multi-login-box-b2bUser-loginBox-terms-and-conditions</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#prehome-login-multi-login-box-b2bUser-loginBox-terms-and-conditions</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53d75aa0-236b-40e5-881a-bb4f87a8609b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e6c296c0-2b26-4017-8b89-1fbba29fe032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prehome-login-multi-login-box-b2bUser-loginBox-terms-and-conditions</value>
      <webElementGuid>cb3ce623-fa56-4cbb-960d-8ecfc204fddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-auto-form-param</value>
      <webElementGuid>260c5e09-b93e-48f6-87a5-daa254ac57b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>prehome-login-multi-login-box-b2bUser-loginBox-terms-and-conditions</value>
      <webElementGuid>02ff828e-8a57-4f6b-8fb3-3aa36371243a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prehome-login-multi-login-box-b2bUser-loginBox-terms-and-conditions&quot;)</value>
      <webElementGuid>77826497-71c3-486e-ad00-a86f3ed917cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prehome-login-multi-login-box-b2bUser-loginBox-terms-and-conditions']</value>
      <webElementGuid>d72c8bb1-c4e4-41ed-a2d4-f543b5e1d2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prehome-login-multi-login-box-b2bUser-loginBox']/div[3]/input</value>
      <webElementGuid>4aff8528-518f-4b5d-976d-024a76a08af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>86c3f0d3-08b3-4ec1-ad94-bfeb25e0200f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'prehome-login-multi-login-box-b2bUser-loginBox-terms-and-conditions' and @name = 'prehome-login-multi-login-box-b2bUser-loginBox-terms-and-conditions']</value>
      <webElementGuid>0f56936d-54c4-455d-b882-83b5e21c736d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
