<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Apellidos_pax-surname</name>
   <tag></tag>
   <elementGuidId>21c9daa9-9f31-4f9a-8878-61e190652723</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pax-surname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pax-surname&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Apellidos...&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0440edc-0714-4ef1-bbdd-05c8b1c9af1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd3013b3-73d4-4001-b80b-b9d68baf18e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pax-surname</value>
      <webElementGuid>33df1f64-8adf-4a06-9fe3-606beb0afbb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control tabbed</value>
      <webElementGuid>08cd10a5-3525-40c8-89b8-b91ef126381b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Apellidos...</value>
      <webElementGuid>13012da4-2191-4fd0-8ad7-ae388029c0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>7d94b78c-6b60-4a4c-84b8-f7af1a5d9928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>name ascii-only pax-duplicate-validation</value>
      <webElementGuid>1e0aae4a-89c9-4c93-aa41-9ede1fa57ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-msg-i18n</name>
      <type>Main</type>
      <value>rqf:you must fill a surname</value>
      <webElementGuid>b3230c19-8ae8-4603-9e19-182963e4124e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;booking-data&quot;]/div[@class=&quot;booking-data__data&quot;]/div[2]/div[@class=&quot;booking-data__section booking-data__paxes&quot;]/div[@class=&quot;booking-data__section-content&quot;]/div[@class=&quot;booking__widget&quot;]/div[@class=&quot;booking-paxes&quot;]/div[@class=&quot;booking-paxes__room&quot;]/div[@class=&quot;booking-paxes__pax&quot;]/div[@class=&quot;booking-paxes__pax-fields&quot;]/label[@class=&quot;booking-paxes__pax-field&quot;]/input[@class=&quot;form-control tabbed&quot;]</value>
      <webElementGuid>29922fec-a7a4-44ae-857a-64406adc94aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pax-surname']</value>
      <webElementGuid>989920dd-c5bf-4204-87aa-3787c86e696a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/div[3]/div[2]/div[3]/div/div[2]/div/div[3]/div/div[2]/label[3]/input</value>
      <webElementGuid>c07f6b3e-2392-42e3-a73f-c02db709ba7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/input</value>
      <webElementGuid>d63e8802-7872-4144-8f1b-9135918bc0c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pax-surname' and @placeholder = 'Apellidos...']</value>
      <webElementGuid>011f6773-4474-4f66-a430-12a240c2ab8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
