<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_F. nacimiento_pax-birthday_1</name>
   <tag></tag>
   <elementGuidId>395abaa9-2704-43b4-b9ef-cd425563f57e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='pax-birthday'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;dd/mm/yyyy&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b2658ac-e441-4a7b-83b7-bfebed112fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f20b638e-142b-40d6-b7d4-75cb0a2e6d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pax-birthday</value>
      <webElementGuid>5b120817-d69c-4a26-ad7e-a49826347c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>09297ded-e138-421f-982e-d1817d25f162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>3c78f74f-7192-4ff9-8b66-057baa4385d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>pax-birthday</value>
      <webElementGuid>0f8f9156-6098-4a52-9cc6-7c3c898607a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-msg</name>
      <type>Main</type>
      <value>IMPORTANTE. Por favor introduce la fecha en el formato dd/mm/yyyy, donde dd es el día, mm es el mes y yyyy es el año.&lt;br />&lt;br />Recuerda que este pasajero es un adulto, por lo que la fecha de nacimiento debe corresponderse con la edad de un adulto (18+ años) cuando comience el viaje</value>
      <webElementGuid>e668c3c1-5c29-4a7f-9b67-218209d7368b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>85fceb6a-d13b-433f-b8a5-0c6f7a60ee48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dateformat</name>
      <type>Main</type>
      <value>dd/MM/yyyy</value>
      <webElementGuid>9477ce22-bc03-437e-a3c0-2185494f2e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;booking-data&quot;]/div[@class=&quot;booking-data__data&quot;]/div[2]/div[@class=&quot;booking-data__section booking-data__paxes&quot;]/div[@class=&quot;booking-data__section-content&quot;]/div[@class=&quot;booking__widget&quot;]/div[@class=&quot;booking-paxes&quot;]/div[@class=&quot;booking-paxes__room&quot;]/div[@class=&quot;booking-paxes__pax&quot;]/div[@class=&quot;booking-paxes__pax-fields&quot;]/label[@class=&quot;booking-paxes__pax-field&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>a6ea2610-1d5d-461f-a0dc-da32a0d5b9c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='pax-birthday'])[2]</value>
      <webElementGuid>2bdf5abc-8ea9-4c4a-b807-e8dbad0b71b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/div[3]/div[2]/div[3]/div/div[2]/div/div[3]/div[2]/div[2]/label[4]/input</value>
      <webElementGuid>803440ee-6daf-4f54-b4cc-04f575e3159e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/label[4]/input</value>
      <webElementGuid>b76fe1b3-8404-403d-87ed-6b4bde006243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pax-birthday' and @placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>445d10a3-d2e5-41b7-bb2f-0f6c97b2f5ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
