<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre_pax-name</name>
   <tag></tag>
   <elementGuidId>33af5bb0-8818-427a-ae2c-36d54cc5047b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pax-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pax-name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Nombre...&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf69aed2-b67c-4eaf-b84a-dc4b94b31ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>44269254-8050-42cb-a9f1-9ca77d97f75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pax-name</value>
      <webElementGuid>81893450-e83e-4d78-92ce-130aae750336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>975cf1d1-f231-4326-8087-2972063bdc09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nombre...</value>
      <webElementGuid>e20389ec-4856-4a9f-8c7f-3eda5d2070ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>d4a8d437-ffe9-45b3-ad5d-8a4ac4d934e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>name ascii-only pax-duplicate-validation</value>
      <webElementGuid>d7ba4f35-4132-49ae-96a4-bb47cea660cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-msg-i18n</name>
      <type>Main</type>
      <value>rqf:you must fill a name</value>
      <webElementGuid>dfbff718-8d1c-4111-85d8-8c0dcba7bc36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;booking-data&quot;]/div[@class=&quot;booking-data__data&quot;]/div[2]/div[@class=&quot;booking-data__section booking-data__paxes&quot;]/div[@class=&quot;booking-data__section-content&quot;]/div[@class=&quot;booking__widget&quot;]/div[@class=&quot;booking-paxes&quot;]/div[@class=&quot;booking-paxes__room&quot;]/div[@class=&quot;booking-paxes__pax&quot;]/div[@class=&quot;booking-paxes__pax-fields&quot;]/label[@class=&quot;booking-paxes__pax-field&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>78e8b0eb-ce95-4016-ae8f-ca37fd5aba7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pax-name']</value>
      <webElementGuid>4de00279-03d3-45b5-a626-f002e1a77425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/div[3]/div[2]/div[3]/div/div[2]/div/div[3]/div/div[2]/label[2]/input</value>
      <webElementGuid>d96fce31-f7c8-483d-9f0e-cfc215ea45b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/input</value>
      <webElementGuid>5d8d4353-23d2-4b16-a060-a61f7f2aa86c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pax-name' and @placeholder = 'Nombre...']</value>
      <webElementGuid>07982e5f-b5c6-4928-937c-1bacddef7ec0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
