<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre_pax-name_1</name>
   <tag></tag>
   <elementGuidId>1ad4bf44-ac38-4c47-92b6-780cc70d1de5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='pax-name'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Nombre...&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0478235e-40fa-48cc-8303-bde474442b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b062d9c9-9c7b-486f-a7b0-1339255f7267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pax-name</value>
      <webElementGuid>08561140-3b9a-4e65-b3ac-8fbd81c77a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b3f0027a-4c52-4b3c-b0f9-ff200ee8286f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nombre...</value>
      <webElementGuid>b0e8bede-fca2-4288-8d31-634eb83bab8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>75fe4629-ae93-4cc8-a7ee-4cf1348f4dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>name ascii-only pax-duplicate-validation</value>
      <webElementGuid>72522f0d-626b-4d14-86ff-4885e898b68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-msg-i18n</name>
      <type>Main</type>
      <value>rqf:you must fill a name</value>
      <webElementGuid>fed63758-ff7d-4cd4-9274-0e4dd3ab16b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;booking-data&quot;]/div[@class=&quot;booking-data__data&quot;]/div[2]/div[@class=&quot;booking-data__section booking-data__paxes&quot;]/div[@class=&quot;booking-data__section-content&quot;]/div[@class=&quot;booking__widget&quot;]/div[@class=&quot;booking-paxes&quot;]/div[@class=&quot;booking-paxes__room&quot;]/div[@class=&quot;booking-paxes__pax&quot;]/div[@class=&quot;booking-paxes__pax-fields&quot;]/label[@class=&quot;booking-paxes__pax-field&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>0b7f8765-3638-4b9c-bc76-7a12dc6f313e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='pax-name'])[2]</value>
      <webElementGuid>06af0dc8-4fd4-43b2-93ea-bfc4ac7ac65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/div[3]/div[2]/div[3]/div/div[2]/div/div[3]/div[2]/div[2]/label[2]/input</value>
      <webElementGuid>6da0ef8d-fc64-438d-9b66-4947201664fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/label[2]/input</value>
      <webElementGuid>7b1ae40d-a121-454f-893f-0351afd76418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pax-name' and @placeholder = 'Nombre...']</value>
      <webElementGuid>3bb5e378-42bf-4798-9dc8-756c93c79540</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
