<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_F. nacimiento_pax-birthday</name>
   <tag></tag>
   <elementGuidId>6d88acfe-882c-40bb-a815-3381ffc7c578</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pax-birthday']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pax-birthday&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;dd/mm/yyyy&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff7eab0f-96b0-4716-a950-0d90660fd408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3c465cc0-37c7-4881-ac42-ae9917855888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pax-birthday</value>
      <webElementGuid>b270d16a-f6ed-4bc7-b223-f6532347ba23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>63d93ca8-d17c-477c-80e3-75be7f3a444b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>72b5567e-a0fc-4464-a4cb-5ad0f210250d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>pax-birthday</value>
      <webElementGuid>d56a4380-dea0-4ba7-9172-6497f719959d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-msg</name>
      <type>Main</type>
      <value>IMPORTANTE. Por favor introduce la fecha en el formato dd/mm/yyyy, donde dd es el día, mm es el mes y yyyy es el año.&lt;br />&lt;br />Recuerda que este pasajero es un adulto, por lo que la fecha de nacimiento debe corresponderse con la edad de un adulto (18+ años) cuando comience el viaje</value>
      <webElementGuid>6f2346a3-0715-4e40-9a72-657b5cadaf3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>167240f7-2f51-40ca-ab7e-cfe90e653e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dateformat</name>
      <type>Main</type>
      <value>dd/MM/yyyy</value>
      <webElementGuid>dce55e09-8fe9-4e12-820c-ef616a2b1bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;booking-data&quot;]/div[@class=&quot;booking-data__data&quot;]/div[2]/div[@class=&quot;booking-data__section booking-data__paxes&quot;]/div[@class=&quot;booking-data__section-content&quot;]/div[@class=&quot;booking__widget&quot;]/div[@class=&quot;booking-paxes&quot;]/div[@class=&quot;booking-paxes__room&quot;]/div[@class=&quot;booking-paxes__pax&quot;]/div[@class=&quot;booking-paxes__pax-fields&quot;]/label[@class=&quot;booking-paxes__pax-field&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>df2f3782-7077-4e67-82e7-ef579a1e6857</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pax-birthday']</value>
      <webElementGuid>1b99961a-369d-4d55-9fdb-187ce21b5d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/div[3]/div[2]/div[3]/div/div[2]/div/div[3]/div/div[2]/label[4]/input</value>
      <webElementGuid>d22efe2c-7ab3-4ba7-9a99-12fc4801aa07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]/input</value>
      <webElementGuid>1b3befb8-c5f5-4c1c-8a5b-555cf06a547c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pax-birthday' and @placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>29f50c60-4571-4588-9416-e58175ec36cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
