<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_---</name>
   <tag></tag>
   <elementGuidId>03effb54-52f1-445c-973a-d855e1680d13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-pax-treatment-t0-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-pax-treatment-t0-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-pax-treatment-t0-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0f52536a-b1cd-495f-8b59-30f02127151a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>57582b9a-3ac4-48b7-b137-f574a0a85861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-pax-treatment-t0-container</value>
      <webElementGuid>692e8231-0d30-4bb2-9724-a8c4e1843967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>---</value>
      <webElementGuid>07961f9f-13f8-453c-a3ad-9d9f3b46c165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---</value>
      <webElementGuid>814f0c64-6503-41e7-84e5-249ac960969e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-pax-treatment-t0-container&quot;)</value>
      <webElementGuid>5acf1a49-9921-4a66-908c-35cfb4c8a2d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-pax-treatment-t0-container']</value>
      <webElementGuid>a7335234-f192-44d6-8a7c-0dbd9c7af10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/div[3]/div[2]/div[3]/div/div[2]/div/div[3]/div/div[2]/label/span[2]/span/span/span</value>
      <webElementGuid>a589420a-4499-4363-ba4f-eb0d3d82c22d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adulto 1'])[1]/following::span[6]</value>
      <webElementGuid>0ec83165-e640-4301-853c-6651668faebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span/span</value>
      <webElementGuid>9819b0ef-09ff-4223-b4cb-7fc19e388dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-pax-treatment-t0-container' and @title = '---' and (text() = '---' or . = '---')]</value>
      <webElementGuid>6759c9a9-334b-4007-a999-15f75a0cdbc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
