<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Seleccione un origen</name>
   <tag></tag>
   <elementGuidId>41c0c24f-737e-4a9f-a3a8-a9a452f836c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-packagesaer-searcher-origin-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-packagesaer-searcher-origin-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-packagesaer-searcher-origin-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a4fabbb2-dc5c-45b4-9809-9ebdba4eb415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>0bda93da-b151-4a32-b434-ecb8c08a1759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-packagesaer-searcher-origin-container</value>
      <webElementGuid>b53fc849-4610-41b3-b58b-3f8f968eccb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione un origen</value>
      <webElementGuid>88b001cb-53fe-4c98-9aa1-881dd6d0e542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-packagesaer-searcher-origin-container&quot;)</value>
      <webElementGuid>0617f101-0bbe-4000-adc8-0baede466a36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-packagesaer-searcher-origin-container']</value>
      <webElementGuid>8e04b7c0-ef86-4e45-bb03-b26d794fb1d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='packagesaer-searcher']/div[2]/div/div/div[2]/span/span/span/span</value>
      <webElementGuid>2df55484-1329-43f1-af03-4e4c02122f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Origen'])[1]/following::span[4]</value>
      <webElementGuid>69f9dc48-0631-463a-bbd8-ab7469d6da8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descubre Colombia'])[2]/following::span[6]</value>
      <webElementGuid>15da0ab7-f899-4bf6-bf61-50b3e2106ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ida'])[1]/preceding::span[4]</value>
      <webElementGuid>245dd719-820f-4469-a28e-7b71c6cee492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/span/span</value>
      <webElementGuid>da9fcd46-cf32-478a-b1ad-1a9fee213842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-packagesaer-searcher-origin-container' and (text() = 'Seleccione un origen' or . = 'Seleccione un origen')]</value>
      <webElementGuid>8f1ea871-ef68-4de7-9510-1664cf917e20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
