<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Seleccione un destino</name>
   <tag></tag>
   <elementGuidId>ef330c81-e053-42b4-b7a0-4d79c48da76f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-packagesaer-searcher-destination-container']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.select2-selection__placeholder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Seleccione un destino&quot;i >> internal:text=&quot;Seleccione un destino&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e9e5e9ec-9444-446a-adbd-b8b5f57a4794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__placeholder</value>
      <webElementGuid>c39cc181-cf3d-4da1-bc92-023d86a2c278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione un destino</value>
      <webElementGuid>4a057edf-072c-445f-86a3-0c5e424e5888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-packagesaer-searcher-destination-container&quot;)/span[@class=&quot;select2-selection__placeholder&quot;]</value>
      <webElementGuid>09ea8d60-6143-4b61-bad6-bfb6c6ff7bcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-packagesaer-searcher-destination-container']/span</value>
      <webElementGuid>02fbb808-aa4a-4778-8324-b058c57fa459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Destino'])[1]/following::span[5]</value>
      <webElementGuid>120d4f4e-b611-4e9a-98b5-9982393e35e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Europamundo'])[2]/following::span[6]</value>
      <webElementGuid>88538596-a410-49d1-9a12-05a784babfb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Origen'])[1]/preceding::span[3]</value>
      <webElementGuid>d9b72f13-7d36-4498-9798-01bd403195ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione un origen'])[1]/preceding::span[3]</value>
      <webElementGuid>4cd2faf3-256c-463c-ac72-1d356ac8be80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span/span</value>
      <webElementGuid>eb0448e8-4a2a-4cf7-9cfc-7fdf8c5327d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Seleccione un destino' or . = 'Seleccione un destino')]</value>
      <webElementGuid>b3e223fa-afcc-4302-8e0b-6ffd29b24155</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
