<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_select_hotel</name>
   <tag></tag>
   <elementGuidId>6e3f3a79-23e3-4e7c-b828-5355f22bc40c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;results-list&quot;]/div[2]/div/div[1]/article/div[1]/div[2]/div[3]/button&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
