<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_pco_inter</name>
   <tag></tag>
   <elementGuidId>3fbf7c04-16d2-400a-9f26-1dc88d82bca1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu-option-packagesDcp']/following::ul[1]//a[normalize-space(text())='Internacional']&#xd;
&#xd;
&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
