<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_change_train</name>
   <tag></tag>
   <elementGuidId>f4c3efc0-dfb4-4f69-aba6-1783dd43479f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[contains(@class,&quot;result-option&quot;)]//button[text()=&quot;Cambiar&quot;])[1]&#xd;
&#xd;
&#xd;
&#xd;
&#xd;
&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
