<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>set_pax_adl_insurance</name>
   <tag></tag>
   <elementGuidId>e23d3b97-3ddf-467c-b3bb-338b68e7ebf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;insurance-searcher-_ctl1__ctl1__ctl1_pageBody_pageBody_searcher__ctl0_ctlRoomSelector-room-selector-button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
