<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Finalizar reserva</name>
   <tag></tag>
   <elementGuidId>9e77626b-ef2a-4148-b6e2-ba7b7ac0c0de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[12]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.confirm-booking__book-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Finalizar reserva&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c7122c78-c73d-4252-ac4e-774548ccd425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>762b7c48-78a6-40cc-8d98-2b73762fcd06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary confirm-booking__book-button </value>
      <webElementGuid>162dc846-acfb-47df-8590-ab367db0ceb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Finalizar reserva</value>
      <webElementGuid>783380f3-0fc4-492a-9d57-32647a57d3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;confirm-booking&quot;]/div[@class=&quot;booking-data&quot;]/div[@class=&quot;booking-data__summary&quot;]/div[@class=&quot;confirm-booking__actions hidden-sm hidden-xs&quot;]/div[@class=&quot;confirm-booking__action-item&quot;]/button[@class=&quot;btn btn-primary confirm-booking__book-button&quot;]</value>
      <webElementGuid>a52320cf-b9a6-463d-b3a3-b4be57d36aab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[12]</value>
      <webElementGuid>e3501cbd-caa4-46b1-b177-257274f1fc11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/div/div/div[2]/div[2]/button</value>
      <webElementGuid>b4ff36e5-c91a-4c37-9f96-9d432a2228ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar cotización'])[1]/following::button[1]</value>
      <webElementGuid>20c032cc-6767-4c43-b414-ffe507f5bc62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 3,416.35 USD'])[2]/following::button[2]</value>
      <webElementGuid>952c4e05-f8fb-4576-9292-2f13b90bd262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promocode'])[1]/preceding::button[1]</value>
      <webElementGuid>4919b756-754b-4a0d-aadd-c86e3947ea0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Introduzca su código promocional y aproveche los descuentos adicionales en su reserva.'])[1]/preceding::button[1]</value>
      <webElementGuid>40944678-a63c-4cba-a904-21aae199decd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Finalizar reserva']/parent::*</value>
      <webElementGuid>1ed378cd-330e-4862-9135-0ffa95627f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div[2]/button</value>
      <webElementGuid>63070582-6a36-4901-8e01-e6e24af42d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Finalizar reserva' or . = 'Finalizar reserva')]</value>
      <webElementGuid>e9d2f6bb-6f62-47b9-98f9-dcc7c6c59c05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
