<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telfono_holder_phone</name>
   <tag></tag>
   <elementGuidId>254502f6-78f2-4040-b89b-9899a2ea1613</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='holder_phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;holder_phone&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;000000&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>276d5367-8738-421c-80d0-00694dc62a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>c54c53f1-8de4-462a-8cb2-b5124e9870ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>holder_phone</value>
      <webElementGuid>c6f60fe8-7ec8-4145-ad2a-ba6c4f2125a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>9cd48130-5a74-40a2-9c44-122aa87749c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1d21c752-2ef4-442c-ad1f-352f5692f343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>000000</value>
      <webElementGuid>fb6e6756-d917-460b-9768-59e6221d4df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>6a36a293-3b2f-497c-b795-8a7c305cea8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-msg-i18n</name>
      <type>Main</type>
      <value>rqf:you must fill a valid phone number</value>
      <webElementGuid>41d6999c-b21c-48ba-b7cc-8fa43e16ba67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>0a88be39-f542-487a-ad5d-aadf8623bd2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;confirm-booking&quot;]/div[@class=&quot;booking-data&quot;]/div[@class=&quot;booking-data__data&quot;]/div[@class=&quot;confirm-booking__section confirm-booking__holder-data&quot;]/fieldset[@class=&quot;confirm-booking__fields&quot;]/label[@class=&quot;confirm-booking__field col-sm-4&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>bd1c3ca6-9246-4cad-a61f-5661ce11bf38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='holder_phone']</value>
      <webElementGuid>e5333de5-57d7-4b3f-837a-451cd42a8169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/div/div[2]/div[2]/fieldset/label[11]/input</value>
      <webElementGuid>49c9c191-ab26-490b-93e6-4a0607d2171e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[11]/input</value>
      <webElementGuid>a61ca316-ba27-4231-a0b2-38446a938039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'holder_phone' and @placeholder = '000000']</value>
      <webElementGuid>44616da4-6cbb-428a-a022-a4fd62e56c1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
