<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Direccin_billing_address</name>
   <tag></tag>
   <elementGuidId>94d4f1b4-e20f-49e4-a7d1-eb0603aebaee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='billing_address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;billing_address&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Dirección\n\t\t\t                    \n                                Por favor, introduzca una dirección.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cfb26d1f-a0a9-44d1-bf4d-3751c1c1670e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95f8a216-7024-4bfa-92cd-5b2dde917ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>16d1b42c-1645-47bb-b49d-f11f39d52df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>c584ce6e-4cfd-4eff-be6c-d4bfbd0f0b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-agencybilling_address</name>
      <type>Main</type>
      <value>C/Son fuster, 33</value>
      <webElementGuid>beeda546-bf68-49e1-826e-6462044b7906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_address</value>
      <webElementGuid>73707551-54cf-4b70-a720-ae5ab17c54b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control tabbed</value>
      <webElementGuid>8fe4a081-f451-4b3c-9253-5af719ee6e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Dirección...</value>
      <webElementGuid>c3194aeb-00fa-4a38-897b-c986310b50ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;confirm-booking&quot;]/div[@class=&quot;booking-data&quot;]/div[@class=&quot;booking-data__data&quot;]/div[@class=&quot;confirm-booking__section confirm-booking__billing&quot;]/fieldset[@class=&quot;confirm-booking__fields&quot;]/label[@class=&quot;confirm-booking__field&quot;]/input[@class=&quot;form-control tabbed&quot;]</value>
      <webElementGuid>f68aa5e6-2262-49ca-97b9-e366ec9d0d9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='billing_address']</value>
      <webElementGuid>d0806df2-c823-4d5d-98ca-f2b7b9578696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/div/div[2]/div[4]/fieldset/label[2]/input</value>
      <webElementGuid>2c0f6481-920d-411c-b65f-26e3d835f453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/fieldset/label[2]/input</value>
      <webElementGuid>ff9e5fbd-5cef-4fb5-888a-188c13f92f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_address' and @placeholder = 'Dirección...']</value>
      <webElementGuid>2e4c7a35-6eaa-45b2-befb-1e443a5949d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
