<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Documento de identidad  Pasaporte_holder_id</name>
   <tag></tag>
   <elementGuidId>9db0b99a-3526-4988-a288-595328fac830</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='holder_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;holder_id&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;000000000A&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>283ce37a-4f49-4986-9253-37259c77c57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>accad090-8bca-4f0e-8b37-b747aa321d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>holder_id</value>
      <webElementGuid>cdbf1cce-4ddd-4f85-aafd-9c546cf1e0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c41afee8-cbc6-425a-83ac-b2d0ed772886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>000000000A</value>
      <webElementGuid>179b2235-44b2-4797-94d3-bb137a34a496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>4abf8d9e-9709-4733-8a20-451533ea71b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>dni</value>
      <webElementGuid>88b3aefa-1d07-4780-8aa1-8b2e06158cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-msg-i18n</name>
      <type>Main</type>
      <value>rqf:required field</value>
      <webElementGuid>7213d8cd-c918-44a0-ae97-d9cac856b0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>documentNumber</value>
      <webElementGuid>ac0a6720-0cdb-41b3-8af2-f3372a67fe16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;confirm-booking&quot;]/div[@class=&quot;booking-data&quot;]/div[@class=&quot;booking-data__data&quot;]/div[@class=&quot;confirm-booking__section confirm-booking__holder-data&quot;]/fieldset[@class=&quot;confirm-booking__fields&quot;]/label[@class=&quot;confirm-booking__field col-sm-5&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>79a49584-403b-45b3-a089-4ccfdbd9ed9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='holder_id']</value>
      <webElementGuid>e08933ba-336b-4c6d-8380-7bdb3c258325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/div/div[2]/div[2]/fieldset/label[4]/input</value>
      <webElementGuid>ff7599ea-4963-47a8-81d8-0dee978db4cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]/input</value>
      <webElementGuid>d2ab9079-e3e0-4088-b926-c5a3246c39c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'holder_id' and @placeholder = '000000000A']</value>
      <webElementGuid>73b307c2-b9c2-4f60-bedc-e1c45156d2e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
