<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Consulte las condiciones_termsAndConditions</name>
   <tag></tag>
   <elementGuidId>c0aa4bf1-bc44-4691-b8e1-9b78b7ec728d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='termsAndConditions']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#termsAndConditions</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;He revisado y acepto las políticas y condiciones de cancelación.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23d69573-11ef-4849-a043-8f609eb419a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ac6b08ce-571a-4b55-86a7-a703dfe0595e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>termsAndConditions</value>
      <webElementGuid>cd0ac082-9ed6-4caa-be88-e20178601601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>termsAndConditions</value>
      <webElementGuid>cbb5df6b-75d7-4137-a1b3-1abcc45a40ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;termsAndConditions&quot;)</value>
      <webElementGuid>3730d6da-4f74-4929-830d-210414b3bb53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='termsAndConditions']</value>
      <webElementGuid>efbc9ee9-f0b5-4428-99db-3bdbee193cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/div/div[2]/div[7]/fieldset/input</value>
      <webElementGuid>5564c605-8217-4331-b227-91ef4c622326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/fieldset/input</value>
      <webElementGuid>7b67ce6a-c783-4d66-88ab-8d66ea272038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'termsAndConditions' and @id = 'termsAndConditions']</value>
      <webElementGuid>f66f7f31-5112-4b3d-b191-4e5244783f40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
