<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tramitado por_booked_by</name>
   <tag></tag>
   <elementGuidId>e9137398-176d-4001-9149-ad73c2789884</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='booked_by']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;booked_by&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Tramitado por...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8bd74691-2dcf-4c2d-8d3c-2a002ba42dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>d0e2d216-2216-425b-90da-0ac16b0e5071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>8c73d6d4-16e7-4fe9-977a-3950d42085af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>booked_by</value>
      <webElementGuid>88551497-49bb-4012-9355-8a31235eaf71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a98bc035-d8b7-46cd-878b-c54dee24c90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tramitado por...</value>
      <webElementGuid>1133ebc1-7503-4904-af34-121c31020a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3274a9db-0eca-492a-a59c-5159fb346dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;confirm-booking&quot;]/div[@class=&quot;booking-data&quot;]/div[@class=&quot;booking-data__data&quot;]/div[@class=&quot;confirm-booking__section confirm-booking__agency-data&quot;]/fieldset[@class=&quot;confirm-booking__fields&quot;]/label[@class=&quot;confirm-booking__field&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>b00d6ae2-2601-4e5b-a020-62c054b90460</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='booked_by']</value>
      <webElementGuid>fa22c3bd-66bf-4897-8e87-1af95d06c1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/div/div[2]/div[3]/fieldset/label[2]/input</value>
      <webElementGuid>78db7f43-425f-471d-b386-a44092af74e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/label[2]/input</value>
      <webElementGuid>5269a317-05aa-4dfd-8061-6e869814f1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'booked_by' and @placeholder = 'Tramitado por...']</value>
      <webElementGuid>b16981ae-6ee0-42c4-b8e6-845446de5fab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
