<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ciudad_holder_city</name>
   <tag></tag>
   <elementGuidId>ea566e05-b901-4e6b-8315-06ddb4340c50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='holder_city']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;holder_city&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ciudad...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54396a69-2a46-475f-a11b-db3c1d14dcfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed895978-b9ed-4162-8891-ab79b86e6406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>holder_city</value>
      <webElementGuid>d3f29c20-8933-4127-b022-45bbd880d5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>029243d5-85e5-4ab1-8b98-12c35881bef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ciudad...</value>
      <webElementGuid>2004e9eb-abdc-448a-b3c0-4a4b41d4b937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>acff1d78-84d5-4756-bbe7-06f395a03695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-msg-i18n</name>
      <type>Main</type>
      <value>rqf:you must fill a city</value>
      <webElementGuid>504d702f-f035-4984-9145-770ed2f8269b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>d949f140-c446-4729-8186-36305921b3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;confirm-booking&quot;]/div[@class=&quot;booking-data&quot;]/div[@class=&quot;booking-data__data&quot;]/div[@class=&quot;confirm-booking__section confirm-booking__holder-data&quot;]/fieldset[@class=&quot;confirm-booking__fields&quot;]/label[@class=&quot;confirm-booking__field col-sm-4&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>7f72a03c-609c-4e80-a688-fc528edfe609</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='holder_city']</value>
      <webElementGuid>3524f32b-1c5f-4329-afb8-54f96849d8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/div/div[2]/div[2]/fieldset/label[6]/input</value>
      <webElementGuid>9ffb8e85-8dfc-4883-948a-9911f2d3e0ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[6]/input</value>
      <webElementGuid>422423e6-028c-4983-8dbb-0f736591b0f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'holder_city' and @placeholder = 'Ciudad...']</value>
      <webElementGuid>64ad62cb-3c29-4654-9f8f-ea4237623da5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
